spring.application.name=proj01

# configuração do BD

# conexão:
spring.datasource.url=jdbc:mysql://localhost:3306/bd_mercado_facens?createDatabaseIfNotExist=true

# dialeto do BD:
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# usuário
spring.datasource.username=profFacens

# senha
spring.datasource.password=aula

# permitir JPA alterar o BD
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true